Задание: Больше деталей
htmlacademy-javascript/160701-keksobooking-26 pull request #3
Opened 2022-07-18 11:19 UTC by DmitrySheklein

2022-07-18 14:05 UTC, PolyDevil requested changes

2022-07-18 14:05 UTC, PolyDevil commented on js/main.js
> +  for (let i = newArr.length - 1; i > 0; i--) {
Вижу ты нашел алгоритм рендомной сортировки.

Как насчет задания чуть посложнее?
У тебя есть функция `getRandomArrayItem` для получение случайного элемента массива, есть метод для случайной сортировки, есть метод для получения случайного куска массива.

Но это три разных функции, ничем не связанные.

Как насчет сделать новый конструктор `ArrayEnhanced`, который бы наследовался от конструктора `Array`, имел бы доступ ко всем нативным методам `Array`, но дополнительно к ним имел бы три метода - `randomElement`, `shuffle`.

Пример использования:
```ts
const a = new ArrayEnhanced(1, 2, 3);
a.shuffle(); // [2,1,3] - вместо мутации возвращает копию массива
a.randomElement() // 2
a instanceof ArrayEnhanced; // true
a instanceof Array; // true
a.map(e => e); // [1, 2, 3]
```

2022-07-18 14:05 UTC, PolyDevil commented on js/main.js
> +        fileNameIndex < 10 ? `0${fileNameIndex}` : fileNameIndex
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String
Здесь есть метод, который позволяет решать такие вещи красиво.

2022-07-18 14:05 UTC, PolyDevil commented on js/main.js
> +      rooms: getRandomInteger(1, 5),
У нас есть методы, которые называются схоже.
Сделать класс Random, который бы имел методы `int`, `float`, `stringFromArray`.
Методы не должны иметь доступа к this, это чистые функции, которые принимают параметры на вход и выдают какое-то значение на выходе (без мутирования состояния).

Вторым условием будет чтобы методы можно было использовать без ключего слова `new`.
```
age: Random.int(2, 7), // валидный синтаксис
```

2022-07-20 07:07 UTC, PolyDevil requested changes

2022-07-20 07:07 UTC, PolyDevil commented on js/main.js
> +    return array[Random.int(0, array.length)];
array.length - 1

2022-07-20 07:07 UTC, PolyDevil commented on js/main.js
> +  static get [Symbol.species]() {
Верно.

2022-07-20 07:07 UTC, PolyDevil commented on js/main.js
> +  constructor(...args) {
Можно не определять конструктор.

2022-07-20 07:07 UTC, PolyDevil commented on js/main.js
> +  constructor(...args) {
Если мы наследуемся через `extends`

2022-07-20 07:07 UTC, PolyDevil commented on js/main.js
> +    const newArr = this.array;
shuffle мутирует текущий массив. Перед рендомной сортировкой клонируй массив.

2022-07-20 07:07 UTC, PolyDevil commented on js/main.js
> +      avatar: `img/avatars/user${String(i).padStart(2, 0)}.png`,
padStart - верно.

2022-07-20 10:28 UTC, DmitrySheklein commented on js/main.js
> +    return array[Random.int(0, array.length)];
@PolyDevil правильнее вызывать внутренний метод как `array[Random.int(0, array.length - 1)]` или `array[this.int(0, array.length - 1)]` ?

2022-07-20 12:14 UTC, PolyDevil requested changes

2022-07-20 12:14 UTC, PolyDevil commented on js/main.js
> +      checkin: getRandomArrayItem(OFFER_TIMES),
Теперь удалить функции getRandomArrayItem и getRandomInteger и оставить только использование методов Random

2022-07-20 12:14 UTC, merged